name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: npm install
        run: npm install

      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          LICENSE_ID: ${{ secrets.LICENSE_ID }}
        run: |
          npm test
          npm run package-ci
          npm run lint
          npm run tsc

# Failing because virtual framebuffer not installed
#          npm run build-e2e
#          npm run test-e2e
