/**
 * This file allows webpack to bundle all of the html generated by the markdown
 * files in this directory into one object that can be imported into the app
 * e.g.  <div dangerouslySetInnerHTML={{ __html: strings.defaultExperiments.facesHouses.overview }} />
 */

import set from 'set-value';

// Unfortunately, recursive globbing doesn't work here,
// so we have to do this somewhat ugly hack.
// @ts-expect-error
import * as firstLevel from 'glob:./**.md';
// @ts-expect-error
import * as secondLevel from 'glob:./**/**.md';
// @ts-expect-error
import * as thirdLevel from 'glob:./**/**/**.md';

// babel-plugin-import-glob separates path with this character
// TODO: directory seperator is not being added so I had to do it manually
const DIRECTORY_SEPARATOR = /_/g;
const buildStrings = () => {
  const entries = { ...firstLevel, ...secondLevel, ...thirdLevel };
  const nested: any = {};
  Object.keys(entries).forEach((key) => {
    const keyWithDots = key.replace(DIRECTORY_SEPARATOR, '.');
    set(nested, keyWithDots, entries[key]);
  });
  return nested;
};

const strings = buildStrings();
export default strings;
